### PR TITLE
Add simple donation button

### PR DESCRIPTION
**Pull request by stophecom**

### CODE REVIEW

**Comment by stophecom** [comment]
screen shot 2015-07-20 at 22 05 29

@njam please review

**Comment by njam** [comment]
lgtm!

Maybe change the "purpose" to be more specific? "Unterstützung für das Festival Frontâle"?
screen shot 2015-07-20 at 22 13 20

**Comment by stophecom** [comment]
Makes sense! Button now in German as well ;) Please verify

**Comment by njam** [comment]
trust you on this!

**Pull request merged**
