### PR TITLE
Add calendar button

### PR DESCRIPTION
**Pull request by stophecom**

### CODE REVIEW

**Comment by stophecom** [comment]
@njam fyi - Button doesn't fit too nicely. Will update whole design as soon we have more infos to publish!

**Comment by stophecom** [comment]
Hm maybe there is a better way to do this. Don't like this plugin too much...

**Comment by njam** [comment]
btw you don't have to add _minimized_ versions of JS (and CSS) - everything get's uglified with grunt!

**Comment by stophecom** [comment]
Good to know. Well, I didn't find another version (Not really an _open source_ plugin it seems - https://addthisevent.com/buttons/add-to-calendar/) - Will reconsider it ;)

**Pull request merged**
